# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 494cbdfe04c2b5b29013af75303821a1cfdc8663d20f64c049d29c30071c704fefe451bbed758fd70c4c9f727d1080c829b5efbf2eae569eab31ed3601037146

test:
  secret_key_base: e8b4ad8737090de42cfbde97a554e0ecb7b54cc78a92fe025acc78b47aa104a5d930f4dd79fa34860a3b9e633419bf3262e27a2db561ea9c1246e3fc07f336bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
